import { MetricDefinition } from "@/types";

export const METRIC_CATALOG: MetricDefinition[] = [
  // ==========================================
  // 1. MEDIA DELIVERY
  // ==========================================
  {
    id: "spend",
    displayName: "Spend",
    platform: "cross_platform",
    category: "Media Delivery",
    dataType: "currency",
    isDerived: false,
    sourceField: "spend",
    description: "Total cost accrued across paid advertising campaigns.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "impressions",
    displayName: "Impressions",
    platform: "cross_platform",
    category: "Media Delivery",
    dataType: "integer",
    isDerived: false,
    sourceField: "impressions",
    description: "Number of times ad creatives or content pieces were displayed on user screens.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad", "country", "device"],
  },
  {
    id: "reach",
    displayName: "Reach",
    platform: "cross_platform",
    category: "Media Delivery",
    dataType: "integer",
    isDerived: false,
    sourceField: "reach",
    description: "Total number of unique user accounts that viewed your ad or content.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "frequency",
    displayName: "Frequency",
    platform: "meta",
    category: "Media Delivery",
    dataType: "ratio",
    isDerived: true,
    formula: "impressions / NULLIF(reach, 0)",
    description: "Average number of times each unique user viewed your ad (Impressions / Reach).",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },
  {
    id: "cpm",
    displayName: "CPM (Cost Per 1,000 Impressions)",
    platform: "cross_platform",
    category: "Media Delivery",
    dataType: "currency",
    isDerived: true,
    formula: "(spend / NULLIF(impressions, 0)) * 1000",
    description: "Average cost incurred per 1,000 impressions delivered.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },

  // ==========================================
  // 2. TRAFFIC
  // ==========================================
  {
    id: "clicks",
    displayName: "Clicks (All)",
    platform: "cross_platform",
    category: "Traffic",
    dataType: "integer",
    isDerived: false,
    sourceField: "clicks",
    description: "Total user clicks on any part of the ad or post component.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "link_clicks",
    displayName: "Link Clicks",
    platform: "meta",
    category: "Traffic",
    dataType: "integer",
    isDerived: false,
    sourceField: "linkClicks",
    description: "Clicks on destination links within ads or social media bio/posts.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "ctr",
    displayName: "Click-Through Rate (CTR %)",
    platform: "cross_platform",
    category: "Traffic",
    dataType: "percentage",
    isDerived: true,
    formula: "(clicks / NULLIF(impressions, 0)) * 100",
    description: "Percentage of impressions that resulted in a user click.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "cpc",
    displayName: "Cost Per Click (CPC)",
    platform: "cross_platform",
    category: "Traffic",
    dataType: "currency",
    isDerived: true,
    formula: "spend / NULLIF(clicks, 0)",
    description: "Average cost paid for each individual user click.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "landing_page_views",
    displayName: "Landing Page Views",
    platform: "meta",
    category: "Traffic",
    dataType: "integer",
    isDerived: false,
    sourceField: "landingPageViews",
    description: "Number of times a user clicked an ad link and successfully loaded the landing page.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },

  // ==========================================
  // 3. VIDEO
  // ==========================================
  {
    id: "video_views",
    displayName: "Video Views",
    platform: "cross_platform",
    category: "Video",
    dataType: "integer",
    isDerived: false,
    sourceField: "videoViews",
    description: "Total video plays recorded on paid or organic videos.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "video_3s_views",
    displayName: "3-Second Video Views",
    platform: "meta",
    category: "Video",
    dataType: "integer",
    isDerived: false,
    sourceField: "video3sViews",
    description: "Number of times a video was played for 3 seconds or longer.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },
  {
    id: "thruplays",
    displayName: "ThruPlays",
    platform: "meta",
    category: "Video",
    dataType: "integer",
    isDerived: false,
    sourceField: "thruplays",
    description: "Number of times a video was played to completion, or for at least 15 seconds.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },
  {
    id: "video_completions",
    displayName: "Video Completions (100%)",
    platform: "cross_platform",
    category: "Video",
    dataType: "integer",
    isDerived: false,
    sourceField: "videoCompletions",
    description: "Number of times a video was watched from start to end.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },
  {
    id: "video_completion_rate",
    displayName: "Video Completion Rate (%)",
    platform: "cross_platform",
    category: "Video",
    dataType: "percentage",
    isDerived: true,
    formula: "(video_completions / NULLIF(video_views, 0)) * 100",
    description: "Percentage of total video starts that watched until completion.",
    supportedDimensions: ["date", "platform", "campaign"],
  },
  {
    id: "video_avg_watch_time",
    displayName: "Average Watch Time",
    platform: "cross_platform",
    category: "Video",
    dataType: "duration_seconds",
    isDerived: false,
    sourceField: "videoAvgWatchTime",
    description: "Average duration in seconds users spent watching the video asset.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },

  // ==========================================
  // 4. ENGAGEMENT
  // ==========================================
  {
    id: "likes",
    displayName: "Likes & Reactions",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "likes",
    description: "Count of post likes, heart reactions, or sentiment endorsements.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "comments",
    displayName: "Comments",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "comments",
    description: "Number of public user comments posted on content.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "shares",
    displayName: "Shares",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "shares",
    description: "Number of times content was reshared or re-posted by users.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "saves",
    displayName: "Saves",
    platform: "instagram",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "saves",
    description: "Number of times Instagram users bookmarked or saved the post/Reel.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "post_engagements",
    displayName: "Total Post Engagements",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "postEngagements",
    description: "Combined count of likes, comments, shares, and saves across posts.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "engagement_rate",
    displayName: "Engagement Rate (%)",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "percentage",
    isDerived: true,
    formula: "(post_engagements / NULLIF(reach, 0)) * 100",
    description: "Percentage of reached user accounts that interacted with content.",
    supportedDimensions: ["date", "platform"],
  },

  // ==========================================
  // 5. SOCIAL AUDIENCE (ORGANIC)
  // ==========================================
  {
    id: "total_followers",
    displayName: "Total Followers",
    platform: "instagram",
    category: "Social Audience",
    dataType: "integer",
    isDerived: false,
    sourceField: "totalFollowers",
    description: "Current follower count for social media account.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "followers_gained",
    displayName: "New Followers Gained",
    platform: "instagram",
    category: "Social Audience",
    dataType: "integer",
    isDerived: false,
    sourceField: "followersGained",
    description: "Number of new accounts that followed the profile within the period.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "net_follower_growth",
    displayName: "Net Follower Growth",
    platform: "instagram",
    category: "Social Audience",
    dataType: "integer",
    isDerived: true,
    formula: "followersGained - followersLost",
    description: "Net change in total followers (Gained minus Lost).",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "profile_visits",
    displayName: "Profile Visits",
    platform: "instagram",
    category: "Social Audience",
    dataType: "integer",
    isDerived: false,
    sourceField: "profileVisits",
    description: "Number of user visits to the main account profile page.",
    supportedDimensions: ["date", "platform"],
  },

  // ==========================================
  // 6. CONTENT PERFORMANCE (ORGANIC)
  // ==========================================
  {
    id: "reel_views",
    displayName: "Reel Views (Plays)",
    platform: "instagram",
    category: "Content",
    dataType: "integer",
    isDerived: false,
    sourceField: "reelViews",
    description: "Total plays on Instagram Reels content.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "story_views",
    displayName: "Story Views",
    platform: "instagram",
    category: "Content",
    dataType: "integer",
    isDerived: false,
    sourceField: "storyViews",
    description: "Total views on Instagram Story slides.",
    supportedDimensions: ["date", "platform"],
  },

  // ==========================================
  // 7. CONVERSION
  // ==========================================
  {
    id: "conversions",
    displayName: "Total Conversions",
    platform: "cross_platform",
    category: "Conversion",
    dataType: "integer",
    isDerived: false,
    sourceField: "conversions",
    description: "Aggregate count of platform-defined conversion events.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "leads",
    displayName: "Leads",
    platform: "cross_platform",
    category: "Conversion",
    dataType: "integer",
    isDerived: false,
    sourceField: "leads",
    description: "Number of form submissions, lead captures, or signups.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "purchases",
    displayName: "Purchases",
    platform: "cross_platform",
    category: "Conversion",
    dataType: "integer",
    isDerived: false,
    sourceField: "purchases",
    description: "Count of completed sales or e-commerce purchase transactions.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "cpa",
    displayName: "Cost Per Acquisition (CPA)",
    platform: "cross_platform",
    category: "Conversion",
    dataType: "currency",
    isDerived: true,
    formula: "spend / NULLIF(conversions, 0)",
    description: "Average cost spent per completed conversion action.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },

  // ==========================================
  // 8. VALUE (OPTIONAL / NON-MANDATORY)
  // ==========================================
  {
    id: "conversion_value",
    displayName: "Conversion Value (Revenue)",
    platform: "cross_platform",
    category: "Value",
    dataType: "currency",
    isDerived: false,
    sourceField: "conversionValue",
    description: "Total monetary value generated from tracked conversions.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "roas",
    displayName: "Return On Ad Spend (ROAS)",
    platform: "cross_platform",
    category: "Value",
    dataType: "ratio",
    isDerived: true,
    formula: "conversionValue / NULLIF(spend, 0)",
    description: "Revenue earned for every $1.00 spent on advertising.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "view_through_conversions",
    displayName: "View-Through Conversions",
    platform: "cross_platform",
    category: "Value",
    dataType: "integer",
    isDerived: false,
    sourceField: "viewThroughConversions",
    description: "Conversions credited to users who saw (but did not click) an ad before converting.",
    supportedDimensions: ["date", "platform", "campaign"],
  },

  // ==========================================
  // 9. TRAFFIC - EXTENDED (platform ads-manager diagnostics)
  // ==========================================
  {
    id: "outbound_clicks",
    displayName: "Outbound Clicks",
    platform: "meta",
    category: "Traffic",
    dataType: "integer",
    isDerived: false,
    sourceField: "outboundClicks",
    description: "Clicks that took people off the platform to an external destination.",
    supportedDimensions: ["date", "platform", "campaign", "adset", "ad"],
  },
  {
    id: "outbound_ctr",
    displayName: "Outbound CTR (%)",
    platform: "meta",
    category: "Traffic",
    dataType: "percentage",
    isDerived: true,
    formula: "(outboundClicks / NULLIF(impressions, 0)) * 100",
    description: "Percentage of impressions that resulted in an outbound click.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },
  {
    id: "unique_clicks",
    displayName: "Unique Clicks",
    platform: "cross_platform",
    category: "Traffic",
    dataType: "integer",
    isDerived: false,
    sourceField: "uniqueClicks",
    description: "Number of unique people who clicked, deduplicated across the period.",
    supportedDimensions: ["date", "platform", "campaign", "adset"],
  },
  {
    id: "unique_ctr",
    displayName: "Unique CTR (%)",
    platform: "cross_platform",
    category: "Traffic",
    dataType: "percentage",
    isDerived: true,
    formula: "(uniqueClicks / NULLIF(reach, 0)) * 100",
    description: "Percentage of reached people who clicked at least once.",
    supportedDimensions: ["date", "platform", "campaign"],
  },
  {
    id: "search_impression_share",
    displayName: "Search Impression Share (%)",
    platform: "google_ads",
    category: "Traffic",
    dataType: "percentage",
    isDerived: false,
    sourceField: "searchImpressionShare",
    description: "Impressions received divided by estimated eligible impressions. Averaged across the period, not summed.",
    supportedDimensions: ["date", "campaign"],
    caveats: "Only reported by Google Ads for Search campaigns.",
  },
  {
    id: "quality_score",
    displayName: "Quality Score",
    platform: "google_ads",
    category: "Traffic",
    dataType: "integer",
    isDerived: false,
    sourceField: "qualityScore",
    description: "Google's 1-10 estimate of ad/keyword/landing-page relevance. Averaged across the period, not summed.",
    supportedDimensions: ["date", "campaign"],
    caveats: "Keyword-level in the real API; averaged to the campaign here.",
  },

  // ==========================================
  // 10. VIDEO - EXTENDED (Meta hook/hold, TikTok short-form)
  // ==========================================
  {
    id: "cost_per_thruplay",
    displayName: "Cost Per ThruPlay",
    platform: "meta",
    category: "Video",
    dataType: "currency",
    isDerived: true,
    formula: "spend / NULLIF(thruplays, 0)",
    description: "Average cost for each 15-second (or completed) video play.",
    supportedDimensions: ["date", "campaign", "adset", "ad"],
  },
  {
    id: "hook_rate",
    displayName: "Hook Rate (%)",
    platform: "meta",
    category: "Video",
    dataType: "percentage",
    isDerived: true,
    formula: "(video3sViews / NULLIF(impressions, 0)) * 100",
    description: "Percentage of impressions that watched at least 3 seconds - how well a creative stops the scroll.",
    supportedDimensions: ["date", "campaign", "ad"],
  },
  {
    id: "hold_rate",
    displayName: "Hold Rate (%)",
    platform: "meta",
    category: "Video",
    dataType: "percentage",
    isDerived: true,
    formula: "(thruplays / NULLIF(video3sViews, 0)) * 100",
    description: "Of people who hooked (3s+), the percentage who kept watching to a ThruPlay.",
    supportedDimensions: ["date", "campaign", "ad"],
  },
  {
    id: "video_views_2s",
    displayName: "2-Second Video Views",
    platform: "tiktok_ads",
    category: "Video",
    dataType: "integer",
    isDerived: false,
    sourceField: "videoViews2s",
    description: "Views of at least 2 seconds.",
    supportedDimensions: ["date", "campaign", "ad"],
  },
  {
    id: "video_views_6s",
    displayName: "6-Second Video Views",
    platform: "tiktok_ads",
    category: "Video",
    dataType: "integer",
    isDerived: false,
    sourceField: "videoViews6s",
    description: "Views of at least 6 seconds.",
    supportedDimensions: ["date", "campaign", "ad"],
  },

  // ==========================================
  // 11. ENGAGEMENT - EXTENDED (Meta diagnostics, community management)
  // ==========================================
  {
    id: "negative_feedback",
    displayName: "Negative Feedback",
    platform: "meta",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "negativeFeedback",
    description: "Hides, reports, and unlikes attributed to the ad or post.",
    supportedDimensions: ["date", "campaign", "ad"],
  },
  {
    id: "negative_feedback_rate",
    displayName: "Negative Feedback Rate (%)",
    platform: "meta",
    category: "Engagement",
    dataType: "percentage",
    isDerived: true,
    formula: "(negativeFeedback / NULLIF(impressions, 0)) * 100",
    description: "Negative feedback as a share of impressions - an early creative-fatigue signal.",
    supportedDimensions: ["date", "campaign"],
  },
  {
    id: "comments_responded",
    displayName: "Comments Responded To",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "integer",
    isDerived: false,
    sourceField: "commentsResponded",
    description: "Comments the account replied to - a community management workload metric.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "response_rate",
    displayName: "Response Rate (%)",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "percentage",
    isDerived: true,
    formula: "(commentsResponded / NULLIF(comments, 0)) * 100",
    description: "Share of comments the account replied to.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "avg_response_time",
    displayName: "Average Response Time",
    platform: "cross_platform",
    category: "Engagement",
    dataType: "duration_seconds",
    isDerived: false,
    sourceField: "avgResponseTimeMinutes",
    description: "Average time to first reply on comments/messages, in minutes. Averaged across the period, not summed.",
    supportedDimensions: ["date", "platform"],
  },

  // ==========================================
  // 12. CONTENT - EXTENDED (Stories, publishing cadence)
  // ==========================================
  {
    id: "story_exits",
    displayName: "Story Exits",
    platform: "instagram",
    category: "Content",
    dataType: "integer",
    isDerived: false,
    sourceField: "storyExits",
    description: "Times people exited out of the Story instead of continuing.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "story_exit_rate",
    displayName: "Story Exit Rate (%)",
    platform: "instagram",
    category: "Content",
    dataType: "percentage",
    isDerived: true,
    formula: "(storyExits / NULLIF(storyViews, 0)) * 100",
    description: "Share of Story views that ended in an exit rather than continuing to the next slide.",
    supportedDimensions: ["date", "platform"],
  },
  {
    id: "posts_published",
    displayName: "Posts Published",
    platform: "cross_platform",
    category: "Content",
    dataType: "integer",
    isDerived: false,
    sourceField: "postsPublished",
    description: "Number of organic posts published in the period - a publishing-cadence metric.",
    supportedDimensions: ["date", "platform"],
  },

  // ==========================================
  // 10. WEB ANALYTICS (Google Analytics 4)
  // ==========================================
  // Every rate here is derived from summed numerators and denominators
  // rather than stored, because GA4's own rate metrics are per-row averages
  // that cannot be re-averaged across days or channels without being wrong.
  {
    id: "sessions",
    displayName: "Sessions",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "sessions",
    description: "Visits to the site. A session ends after 30 minutes of inactivity.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "engaged_sessions",
    displayName: "Engaged Sessions",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "engagedSessions",
    description: "Sessions lasting over 10 seconds, or with a key event, or with 2+ pageviews.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "total_users",
    displayName: "Users",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "totalUsers",
    description: "Distinct users who visited the site.",
    supportedDimensions: ["date", "channel", "device"],
    caveats:
      "Users are de-duplicated by GA4 within each row, so summing across days or channels counts a returning visitor once per row and overstates the true unique total. Read it as a trend, not an exact headcount. Sessions is the safe additive equivalent.",
  },
  {
    id: "new_users",
    displayName: "New Users",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "newUsers",
    description: "Users who visited the site for the first time in the period.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "page_views",
    displayName: "Page Views",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "screenPageViews",
    description: "Total pages viewed, including repeat views of the same page.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "web_engagement_rate",
    displayName: "Engagement Rate (Site)",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "percentage",
    isDerived: true,
    formula: "(engagedSessions / NULLIF(sessions, 0)) * 100",
    description: "Share of sessions that were engaged rather than immediate exits.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "bounce_rate",
    displayName: "Bounce Rate",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "percentage",
    isDerived: true,
    formula: "100 - ((engagedSessions / NULLIF(sessions, 0)) * 100)",
    description: "Share of sessions that were not engaged. In GA4 this is the exact inverse of engagement rate.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "avg_session_duration",
    displayName: "Avg. Session Duration",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "duration_seconds",
    isDerived: true,
    formula: "userEngagementDuration / NULLIF(sessions, 0)",
    description: "Average time on site per session.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "pages_per_session",
    displayName: "Pages Per Session",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "ratio",
    isDerived: true,
    formula: "screenPageViews / NULLIF(sessions, 0)",
    description: "Average number of pages viewed in a single visit.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "key_events",
    displayName: "Key Events (Conversions)",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "keyEvents",
    description: "Events marked as key events in GA4 - form submits, sign-ups, purchases and so on.",
    supportedDimensions: ["date", "channel", "device"],
    caveats: "Counts only the events explicitly flagged as key events in the GA4 property. If none are configured this reads zero, which is a property setup gap rather than a reporting fault.",
  },
  {
    id: "site_conversion_rate",
    displayName: "Site Conversion Rate",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "percentage",
    isDerived: true,
    formula: "(keyEvents / NULLIF(sessions, 0)) * 100",
    description: "Share of sessions that produced a key event.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "transactions",
    displayName: "Transactions",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "integer",
    isDerived: false,
    sourceField: "transactions",
    description: "Completed ecommerce purchases recorded on the site.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "web_revenue",
    displayName: "Site Revenue",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "currency",
    isDerived: false,
    sourceField: "totalRevenue",
    description: "Total revenue recorded by GA4, in the property's reporting currency.",
    supportedDimensions: ["date", "channel", "device"],
  },
  {
    id: "avg_order_value",
    displayName: "Average Order Value",
    platform: "google_analytics",
    category: "Web Analytics",
    dataType: "currency",
    isDerived: true,
    formula: "totalRevenue / NULLIF(transactions, 0)",
    description: "Revenue divided by completed transactions.",
    supportedDimensions: ["date", "channel", "device"],
  },
];

// Custom (agency-defined) metrics live in Supabase (see supabase-data.ts's
// fetchCustomMetrics/saveCustomMetricToSupabase), but every metric lookup
// in this file needs to stay synchronous - query-engine.ts and every
// widget's render path call these directly, and making them async would
// cascade into an async refactor of the entire widget system for a
// feature that's read far more often than it's written. Instead: a
// module-level cache, populated once per session (see setCustomMetricsCache,
// called from AgencyShell/ClientPortalShell after fetching from Supabase)
// and refreshed whenever a custom metric is created/deleted.
let customMetricsCache: MetricDefinition[] = [];

export function setCustomMetricsCache(metrics: MetricDefinition[]) {
  customMetricsCache = metrics;
}

// Custom (agency-defined) metrics are merged in wherever the catalog is
// read from, so they show up in the same picker/browser as built-in
// metrics without every call site needing to know they exist separately.
function getEffectiveCatalog(): MetricDefinition[] {
  return [...METRIC_CATALOG, ...customMetricsCache];
}

export function getMetricById(id: string): MetricDefinition | undefined {
  return getEffectiveCatalog().find((m) => m.id === id);
}

export function getMetricsByCategory(category: string): MetricDefinition[] {
  return getEffectiveCatalog().filter((m) => m.category === category);
}

export function getMetricsByPlatform(platform: string): MetricDefinition[] {
  return getEffectiveCatalog().filter(
    (m) => m.platform === "cross_platform" || m.platform === platform
  );
}

export function getAllMetrics(): MetricDefinition[] {
  return getEffectiveCatalog();
}
